/*
 * Copyright (C) 2021 GS United Labs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 *  Project    :   FakeDockingPoC
 *  Class      :   FakeDockingFrame.java
 *  Author     :   Sean Carrick
 *  Created    :   Dec 7, 2021 @ 2:15:52 PM
 *  Modified   :   Dec 7, 2021
 *  
 *  Purpose:
 *  
 *  Revision History:
 *  
 *   WHEN          BY                  REASON
 *   ------------  ------------------- ------------------------------------------
 *  Dec 07, 2021  Sean Carrick        Initial creation.
 * *****************************************************************************
 */
package com.gs.api.desktop.testing;

import com.gs.api.desktop.docking.Dockable;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Sean Carrick
 */
public class FakeDockingFrame extends javax.swing.JFrame {
    
    private static int editorCount = 0;
    private static int navigatorCount = 0;
    private static int propertiesCount = 0;
    private static int outputCount = 0;
    
    /**
     * Creates new form FakeDockingFrame
     */
    public FakeDockingFrame() {
        initComponents();
        
        setSize(new Dimension(800, 600));
        
//        outputSplit.setDividerLocation(1.0d);
//        outputSplit.setDividerSize(0);
//        
//        totalSplit.setDividerLocation(0.0d);
//        totalSplit.setDividerSize(0);
//        
//        editorSplit.setDividerLocation(1.0d);
//        editorSplit.setDividerSize(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalSplit = new javax.swing.JSplitPane();
        outputSplit = new javax.swing.JSplitPane();
        editorSplit = new javax.swing.JSplitPane();
        editorPane = new javax.swing.JTabbedPane();
        propertiesPane = new javax.swing.JTabbedPane();
        outputPane = new javax.swing.JTabbedPane();
        navigatorPane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newEditorMenuItem = new javax.swing.JMenuItem();
        newOutputMenuItem = new javax.swing.JMenuItem();
        newPropertiesMenuItem = new javax.swing.JMenuItem();
        newNavigatorMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalSplit.setDividerLocation(200);
        totalSplit.setDividerSize(5);
        totalSplit.setResizeWeight(0.25);

        outputSplit.setDividerLocation(500);
        outputSplit.setDividerSize(5);
        outputSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        outputSplit.setResizeWeight(0.75);

        editorSplit.setDividerLocation(400);
        editorSplit.setDividerSize(5);
        editorSplit.setResizeWeight(0.75);
        editorSplit.setLeftComponent(editorPane);
        editorSplit.setRightComponent(propertiesPane);

        outputSplit.setTopComponent(editorSplit);
        outputSplit.setRightComponent(outputPane);

        totalSplit.setRightComponent(outputSplit);
        totalSplit.setLeftComponent(navigatorPane);

        fileMenu.setText("File");

        newEditorMenuItem.setText("New Editor Window");
        newEditorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEditorMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newEditorMenuItem);

        newOutputMenuItem.setText("New Output Window");
        fileMenu.add(newOutputMenuItem);

        newPropertiesMenuItem.setText("New Properties Window");
        fileMenu.add(newPropertiesMenuItem);

        newNavigatorMenuItem.setText("New Navigator Window");
        fileMenu.add(newNavigatorMenuItem);
        fileMenu.add(jSeparator1);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void newEditorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEditorMenuItemActionPerformed
        // Create a new DockingTab.
        editorCount++;
        JPanel editor = new JPanel();
        JLabel label = new JLabel("I am an editor window.");
        editor.add(label);
        editor.setOpaque(false);
        editorPane.add(editor);
        editorPane.setTabComponentAt(editorPane.indexOfComponent(editor), 
                Dockable.getTitlePanel(editorPane, editor, "Editor Window " 
                        + editorCount, false));
        
    }//GEN-LAST:event_newEditorMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FakeDockingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane editorPane;
    private javax.swing.JSplitPane editorSplit;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane navigatorPane;
    private javax.swing.JMenuItem newEditorMenuItem;
    private javax.swing.JMenuItem newNavigatorMenuItem;
    private javax.swing.JMenuItem newOutputMenuItem;
    private javax.swing.JMenuItem newPropertiesMenuItem;
    private javax.swing.JTabbedPane outputPane;
    private javax.swing.JSplitPane outputSplit;
    private javax.swing.JTabbedPane propertiesPane;
    private javax.swing.JSplitPane totalSplit;
    // End of variables declaration//GEN-END:variables
}
